### ISSUE TITLE
Request: Render Container Using React.Fragment

### ISSUE THREAD

**Issue by Undistraction** [rehypejs/rehype-react#9]
Currently it appears that the children of the AST are automatically wrapped in `<div>`. It would be nice if there was an option to use [React.Fragment](https://reactjs.org/docs/fragments.html) instead to avoid unnecessary markup. 

Here is an example of an AST that results in this behaviour:
```
htmlAst:
  children:  [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
  data: {quirksMode: false}
  type: "root"
```
